### ISSUE TITLE
fullsize dataset

### ISSUE THREAD

**Issue by gungui98** [echonet/dynamic#16]
Hi
Thanks for the dataset you have already with the public to reproduce the result. Do you have any plan to share the full-size dataset without any down-sample and post-processing?

**Comment by douyang** [comment]
Thanks for the interest. Due to the sensitive nature of medical imaging, there are a few barriers to open release and this is an ongoing discussion with multiple stakeholders in the university and hospital. In the meantime, please feel free to reach out to the authors if you are associated with a university and can be added to our IRB as part of a collaboration.
